### ISSUE TITLE
Support private model endpoint

### ISSUE THREAD

**Issue by LululuAlu** [arshad-yaseen/monacopilot#11]
Hi, it is great plugin. Consider support private model service such implement open api interface protocol.
```
const copilot = new Copilot(process.env.OPENAI_API_KEY, {
  provider: 'openai',
  model: 'private',
  endpoint: 'http://xxxxxx (private service)',
});
```

**Comment by arshad-yaseen** [comment]
Hey, Thanks for the suggestion! We’ll look into it and keep you updated. Count on it!!

**Comment by arshad-yaseen** [comment]
We have released `v0.9.29` 🎉! Please update and refer to the [Custom Model](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#custom-model) documentation.

**Comment by arshad-yaseen** [comment]
Feel free to reach out if you need anything else. I'm here to help.

**Comment by LululuAlu** [comment]
perfect!
