### ISSUE TITLE
Ability to change system prompt

### ISSUE THREAD

**Issue by dnna** [arshad-yaseen/monacopilot#12]
Thank you for creating this package! One issue I have noticed is that the system prompt seems to be hardcoded here https://github.com/arshad-yaseen/monacopilot/blob/7d6db315d530ea6cb9511abfa493b4b8b9de46b9/src/helpers/prompt.ts#L34 and is impossible to update without patching the library. Would it be possible to expose it as a parameter so the user can set more appropriate system prompts for specific use-cases?

**Comment by arshad-yaseen** [comment]
Hey, Thanks for bringing this up! We’ll explore making the entire prompt configurable and keep you posted.

**Comment by arshad-yaseen** [comment]
We have released `v0.9.24` 🎉. Please upgrade `monacopilot` to the latest version first and refer to this [Custom Prompt](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#custom-prompt) documentation.

**Comment by arshad-yaseen** [comment]
Feel free to let me know if you need anything else. I'm here to help.

**Comment by dnna** [comment]
Wow that was fast, thanks a lot!
