### ISSUE TITLE
Support o1-preview and o1-mini models for openai provider

### ISSUE THREAD

**Issue by dnna** [arshad-yaseen/monacopilot#14]
I'm trying to use OpenAI's new model o1-mini, but monacopilot refuses to run them with the following error:
`Error: Model o1-mini is not supported by openai provider. Supported models: gpt-4o and gpt-4o-mini`

Is it possible to add them to the list of supported models?

**Comment by arshad-yaseen** [comment]
Hey @dnna, The new models `o1-preview` and `o1-mini` have been added to the supported models list with the latest release `v0.9.25` 🚀. Please update and try again.

**Comment by arshad-yaseen** [comment]
Hey @dnna, Sure! Keep you posted!

**Comment by arshad-yaseen** [comment]
Hey @dnna, The new models `o1-preview` and `o1-mini` have been added to the supported models list with the latest release `v0.9.26` 🚀. Please update and try again.

**Comment by dnna** [comment]
Amazing!
