### ISSUE TITLE
issue integrating openrouter as custom model 

### ISSUE THREAD

**Issue by ShamanicArts** [arshad-yaseen/monacopilot#18]
Description:
I encountered an issue while trying to integrate the OpenRouter API as a custom provider in the Monacopilot library. Despite following the documentation and configuring the custom model correctly, I receive an error message stating that the 'openrouter' provider is not supported.
Steps to Reproduce:

Install the latest version of the Monacopilot library (version 0.9.29).
Configure the custom model for the OpenRouter API using the setupOpenRouter function as follows:

```js

function setupOpenRouter(apiKey, options) {
    console.log("Setting up OpenRouter with API key:", apiKey);
    console.log("Options:", options);

    return {
        provider: 'openrouter',
        model: {
            config: (apiKey, prompt) => ({
                endpoint: 'https://openrouter.ai/api/v1/chat/completions',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${apiKey}`,
                },
                body: JSON.stringify({
                    model: options.model || 'deepseek/deepseek-chat',
                    messages: [
                        { role: 'system', content: prompt.system || '' },
                        { role: 'user', content: prompt.user }
                    ],
                }),
            }),
            transformResponse: (response) => ({
                completion: response.choices[0].message.content,
            }),
        },
    };
}
```
Initialize Monacopilot with the custom provider:

```js

initializeMonacopilot(monaco, editor, initialLanguage, {
    provider: 'openrouter',
    model: 'deepseek/deepseek-chat',

    useExternalContext: false,
    useTechnologies: true,
    useCustomPrompt: false,
});
```
Attempt to use the Monacopilot library with the custom provider.

Expected Result:
The Monacopilot library should successfully integrate with the OpenRouter API using the custom provider configuration. Completion requests should be sent to the OpenRouter API, and the response should be processed and returned by Monacopilot.
Actual Result:
An error is thrown by the Monacopilot library, stating that the 'openrouter' provider is not supported. The error message is as follows:

```
monacopilot_config.js:68 Error in Copilot request: Error: Unsupported provider: openrouter
    at ne (index.mjs:34:1607)
    at q.prepareRequest (index.mjs:34:2324)
    at q.complete (index.mjs:34:2770)
    at window.fetch (monacopilot_config.js:61:62)
    at J (index.mjs:8:443)
    at Object.ge [as POST] (index.mjs:8:621)
    at ae (index.mjs:38:1022)
    at index.mjs:7:574
```
The error occurs in the ne function of the Monacopilot library, which checks if the provided provider is supported. It seems that the library has a predefined list of supported providers, and if the provider is not found in that list, it throws the "Unsupported provider" error.
Additional Information:

Monacopilot library version: 0.9.29
Browser: Google Chrome embedded frameworks 
Operating System: Windows 10

I have double-checked the configuration and followed the documentation for setting up a custom model in Monacopilot. The configuration aligns with the example provided in the documentation, but the error persists.
Could you please investigate this issue and provide guidance on how to properly integrate a custom provider like OpenRouter with the Monacopilot library? If there are any specific requirements or limitations for custom providers, it would be helpful to have that information documented.
Thank you for your attention to this matter. Please let me know if you need any further information or clarification.

**Comment by arshad-yaseen** [comment]
You don’t need to pass the provider as 'openrouter'. The provider only accepts the built-in providers in Monacopilot. If you want to connect a custom provider, simply provide the model with its configuration. Also, you don’t need to JSON stringify the body; Monacopilot will handle that. For example, do this approach for your case:

```javascript
function setupOpenRouter(apiKey, options) {
    console.log("Setting up OpenRouter with API key:", apiKey);
    console.log("Options:", options);

    return {
        model: {
            config: (apiKey, prompt) => ({
                endpoint: 'https://openrouter.ai/api/v1/chat/completions',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${apiKey}`,
                },
                body: {
                    model: options.model || 'deepseek/deepseek-chat',
                    messages: [
                        { role: 'system', content: prompt.system || '' },
                        { role: 'user', content: prompt.user }
                    ],
                },
            }),
            transformResponse: (response) => ({
                completion: response.choices[0].message.content,
            }),
        },
    };
}
```

Sorry for the confusing documentation. I will update it. Thank you!

**Comment by arshad-yaseen** [comment]
Documentation Updated!
