### ISSUE TITLE
Feature Request: Add Option to Limit GROQ Context to Prevent Rate Limiting

### ISSUE THREAD

**Issue by ShamanicArts** [arshad-yaseen/monacopilot#24]
Description:
The current integration with GROQ as a provider for MonacoPilot offers fast completions, but it has a notable limitation: GROQ is rate limited and does not currently offer a pay-as-you-go (PAYG) option. This becomes particularly problematic when working with longer code files (i.e., files with more than 80-90 lines of code), as users often hit the rate limit.

In the attached video, I demonstrate the issue where GROQ rate limiting occurs while working with a longer code file.

Issue:
Provider: GROQ
Problem: Rate limiting on completions when working with files longer than approximately 80-90 lines of code.
Impact: The rate limit is frequently hit during active development sessions, which significantly disrupts the workflow.
Workaround: At present, there is no built-in mechanism to handle or prevent this in MonacoPilot, leading to a poor user experience when working on larger projects.
Proposed Solution:
To alleviate this issue, I propose the following feature:

Add a built-in function to MonacoPilot that limits the context length sent to GROQ completions.
Details:
A configurable setting that limits the code context (e.g., number of lines, tokens, or characters) sent to the provider, keeping it under the rate-limiting threshold.
The feature could either trim the context automatically based on configurable thresholds or allow users to manually adjust the context size when GROQ is selected as the provider.
The default configuration could aim to stay within the limits to prevent the rate limiting issue.
Benefits:
Improved user experience with GROQ without hitting rate limits as frequently.
Ability to handle larger code files efficiently by working within the known constraints of GROQ’s API.
Additional Context:
A video demonstration of the issue can be found here: [[Link to video].](https://www.youtube.com/watch?v=P4gy7th3Qrg)
( while the example is a bit nonsensical, it does represent real behaviour in larger code files )
GROQ currently does not offer a pay-as-you-go option, and this feature could offer a viable workaround for longer development sessions.

**Comment by arshad-yaseen** [comment]
Count on it!

**Comment by arshad-yaseen** [comment]
Hey, Update Monacopilot to the latest `v0.10.5` and refer to the [maxContextLines documentation](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#max-context-lines).

**Comment by ShamanicArts** [comment]
Perfect, just implemented my end and seems to work perfectly, some refactoring was needed to handle change from registerCopilot to registerCompletion but otherwise was smooth sailing

**Comment by arshad-yaseen** [comment]
No worries! The `registerCopilot` function was only deprecated and will still be around for a little while longer. However, it's a good idea to update it to `registerCompletion` 😆.
