### ISSUE TITLE
broken motivation image on readme 

### ISSUE THREAD

**Issue by ShamanicArts** [arshad-yaseen/monacopilot#25]
the image linked under the motivation header of the readme is broken

![image](https://github.com/user-attachments/assets/f20ffc55-e750-4b80-8585-0ee47edaf9a2)

visiting the link from github readme displays this 
![image](https://github.com/user-attachments/assets/823808de-b00e-4a0c-906e-e64821090900)

though manually visiting the link as seen in the commit shows the proper image 

![image](https://github.com/user-attachments/assets/1c180c55-e83b-4cc0-917b-d14b6942c9f3)

< funnily enough I saw this comment when I was first looking for ai code completion for my monaco editor, before I found monacopilot! funny to see it here again! >

**Comment by arshad-yaseen** [comment]
> < funnily enough I saw this comment when I was first looking for ai code completion for my monaco editor, before I found monacopilot! funny to see it here again! >

😆

**Comment by arshad-yaseen** [comment]
But it's showing properly for me 🤔

<img width="864" alt="Screenshot 2024-09-21 at 12 39 13 AM" src="https://github.com/user-attachments/assets/25df6b2a-be29-4fb3-97c6-3ee4d0c1b821">

**Comment by arshad-yaseen** [comment]
Maybe there's a caching issue or something else with your browser?

**Comment by ShamanicArts** [comment]
> But it's showing properly for me 🤔
> 
> <img alt="Screenshot 2024-09-21 at 12 39 13 AM" width="864" src="https://private-user-images.githubusercontent.com/104856374/369528336-25df6b2a-be29-4fb3-97c6-3ee4d0c1b821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTk3MjEsIm5iZiI6MTcyNjg1OTQyMSwicGF0aCI6Ii8xMDQ4NTYzNzQvMzY5NTI4MzM2LTI1ZGY2YjJhLWJlMjktNGZiMy05N2M2LTNlZTRkMGMxYjgyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxOTEwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2UxNWNkNzM1OTMzNmJmZjdkMmRjNjM5ZDU2NjcwYjhmYTkzZjc0ZjY5ODU3N2VhOTFmZDQ3M2FlNmNmNDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WLXBYif0x7a6uDKf3flY9Gq9LQoF6FFAmFW338QAlls">



interesting. I just tested on another machine on Opera ( my main browser ) & also on firefox & edge, & I see the same behaviour - I guess it could potentially be a github caching issue

**Comment by arshad-yaseen** [comment]
Got it!

**Comment by arshad-yaseen** [comment]
Btw, Taking a look to it.
