### ISSUE TITLE
Feature Request: onInput or onKeyCommand Trigger for Code Completion

### ISSUE THREAD

**Issue by ShamanicArts** [arshad-yaseen/monacopilot#26]
Description:

We would like to propose the introduction of a third trigger method for Monacopilot code completions, in addition to the existing onIdle and onTyping options. This new method, tentatively named onInput (or onKeyCommand), would allow developers to trigger code completions manually based on specific key commands (e.g., pressing a keyboard shortcut).

Additionally, we suggest that this key command could be used to force-trigger or re-trigger completion responses, even when using the existing onIdle or onTyping methods. This would provide more flexibility to the user, allowing them to manually invoke completions regardless of the trigger mode in use.

Motivation:

Currently, Monacopilot provides two triggering mechanisms:

onIdle: Completion suggestions are triggered after a brief pause in typing.
onTyping: Suggestions appear in real-time as the user types.
While these options are useful in many scenarios, there are cases where developers may want more control over when completions are triggered. For example:

Reducing the frequency of background requests for models with higher response latency or cost.
Providing completions only when specifically requested by the user to avoid distractions from frequent suggestions.
Forcing a new completion request even when a suggestion has already been made (e.g., refining a completion by re-triggering it after making an edit).
The onInput (or onKeyCommand) method would allow code completions to be triggered only when a designated keyboard command is executed (such as Ctrl + Enter). This would enhance user control and could also be beneficial in performance-constrained environments.

In addition, allowing the key command to force-trigger or re-trigger completions would provide a useful escape hatch for users of the onIdle or onTyping modes who want manual intervention, especially in cases where they:

Want to refine a suggestion after it has been generated.
Prefer manual re-triggering without waiting for another idle or typing event.
Proposed Solution:

New Trigger Option: A third option, onInput, would be added to the trigger parameter when registering the completion handler:

```js

registerCompletion(monaco, editor, {
  // ...other options
  trigger: 'onInput',  // Or 'onKeyCommand'
});
```
Manual Triggering via Key Command: Completions would only be triggered when the user performs a specific action, like pressing a keyboard shortcut (e.g., Ctrl + Space). This key command could be customizable through Monaco Editor's existing command/key binding APIs.

Force Trigger for onIdle or onTyping: Even when using onIdle or onTyping, users could manually trigger a completion at any time by pressing a key command (e.g., Ctrl + Enter). This would either:

Initiate a new completion request if no request is pending.
Re-trigger a new completion to refine suggestions after one has already been made.
Example Usage: Here's how the new trigger could be configured:
```js

import * as monaco from 'monaco-editor';
import { registerCompletion } from 'monacopilot';

const editor = monaco.editor.create(document.getElementById('container'), {
  language: 'javascript',
});

// Register completion with 'onInput' trigger method
registerCompletion(monaco, editor, {
  endpoint: 'https://api.example.com/complete',
  language: 'javascript',
  trigger: 'onInput',  // Or 'onKeyCommand'
});

// Set up a keyboard shortcut (e.g., Ctrl + Space) to trigger or re-trigger completion
editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Space, () => {
  // Call completion manually when key command is used
  editor.trigger('keyboard', 'editor.action.triggerSuggest', {});
});

```
When using the onIdle or onTyping modes, pressing the key command could force an immediate completion request:
```js
registerCompletion(monaco, editor, {
  endpoint: 'https://api.example.com/complete',
  language: 'javascript',
  trigger: 'onIdle',  // or 'onTyping'
});

// Allow key command (Ctrl + Space) to force or re-trigger completion
editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Space, () => {
  editor.trigger('keyboard', 'editor.action.triggerSuggest', {});
});

```
Benefits:

User Control: Users can manually request completions when needed, reducing the number of background requests and improving focus. In onIdle or onTyping modes, it allows the user to bypass waiting or re-trigger suggestions at will.
Reduced Resource Usage: By reducing unnecessary completion triggers, it can be particularly useful for expensive models or performance-constrained environments.
Improved Flexibility: Allows users to map completion triggering to specific workflows or keyboard shortcuts, improving flexibility and productivity.
Refinement of Suggestions: Users can force re-trigger completions to refine suggestions, which can be particularly helpful when the initial suggestion isn't fully accurate or requires additional context.
Conclusion:

Adding an onInput or onKeyCommand trigger method, along with the ability to force-trigger or re-trigger completions, would provide developers with greater control over Monacopilot's completion behavior. This feature would enhance flexibility and precision, giving users more control over the completion process in both manual and automated scenarios.

**Comment by arshad-yaseen** [comment]
Thanks! I'm on it and will keep you posted!

**Comment by arshad-yaseen** [comment]
Hey, Update `monacopilot` to `v0.10.6` 🚀. Here is the link: [Manually Trigger Completions](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#manually-trigger-completions)

**Comment by shamanicvocalarts** [comment]
after updating to 0.10.6 I dont seem to get any completions, even on older methods. just changing my import from cdn, without changing anything else in my project, results monacopilot failing to initialise. 

```import { Copilot, registerCompletion } from 'https://unpkg.com/monacopilot@0.10.5/build/index.mjs';```

works fine but 

```import { Copilot, registerCompletion } from 'https://unpkg.com/monacopilot@0.10.6/build/index.mjs';```

does not. 

unfortunately my project is deployed in an environment where it is non-trivial to use NPM or other package management methods so I am unable to test if this is just a cdn issue at this time

**Comment by arshad-yaseen** [comment]
If you have any questions, lmk!

**Comment by ShamanicArts** [comment]
Thanks Arshad! It seems to work fine, though I am having some, I believe unrelated, implementation issues . will confirm if working as expected once I've resolved those issues.

**Comment by ShamanicArts** [comment]
can confirm everything works as expected!
