### ISSUE TITLE
monaco editor version

### ISSUE THREAD

**Issue by wuhanjun** [arshad-yaseen/monacopilot#29]
Starting from what version of monaco editor does it support?

**Comment by arshad-yaseen** [comment]
From `v0.38.0`!

**Comment by wuhanjun** [comment]
> From `v0.38.0`!

Thank you very much for your reply. I am currently using version 0.34.1. May I ask what feature requires an upgrade to v0.38.0?

**Comment by arshad-yaseen** [comment]
Yes, the Monacopilot core is `InlineCompletion`, a feature introduced in `v0.37.0`, which became stable in `v0.38.0`. Just curious—why not upgrade your Monaco editor to the latest version? 😆

**Comment by arshad-yaseen** [comment]
Yes, to work Monacopilot in Monaco editor, we need the `InlineCompletion` feature in the Monaco editor, which was introduced in `v0.37.0` and became stable in `v0.38.0`.

**Comment by arshad-yaseen** [comment]
Just curious—why not upgrade your Monaco editor to the latest version? 😆

**Comment by wuhanjun** [comment]
Because many of our businesses use monaco editor and encapsulate commonly used logic, most of them now use 0.21. If we upgrade, there will be some API changes that require regression testing. I will try upgrading to 0.0.38, and currently it seems to be possible. Thank you!

**Comment by nyan-left** [comment]
Just a quick note that monaco version ranges are now specified in peer deps:
https://github.com/arshad-yaseen/monacopilot/blob/main/packages/monacopilot/package.json#L47
