### ISSUE TITLE
custom front-end part

### ISSUE THREAD

**Issue by wuhanjun** [arshad-yaseen/monacopilot#30]
Hello, How can I customize headers, catch errors, etc. when I only need to access the front-end part?

**Comment by arshad-yaseen** [comment]
Hey, the `registerCompletion` function and `copilot.complete` handle errors internally by logging them with appropriate messages and ignoring them. Both functions will not throw errors. However, if you prefer to handle the errors yourself, I can create a new option called `throwOnError` for both functions. This option would prevent logging and ignoring the errors, and instead, throw them. What do you think?

**Comment by arshad-yaseen** [comment]
Which headers do you need to customize from frontend? Is it in the request going from the frontend to the API where you set up `copilot.complete`, or in the request going to the AI model?

**Comment by wuhanjun** [comment]
Because I only used the front-end part of the monacopilot, the back-end part was implemented by our company's server-side colleagues themselves, without using Node.

When used in my project, we will add some custom attributes required by the business itself in the request header. In addition, we also need to notice the user with an error message when the interface encounters an error, or redirect to a single sign on site when not logged in.

**Comment by arshad-yaseen** [comment]
I understand.

Already on it, Keep you posted!

**Comment by arshad-yaseen** [comment]
Hey, here's an update: please update *monacopilot* to the latest version (v0.10.19 🚀).

Refer to the following:

- [Request Options](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#request-options)
- [Handling Errors](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#handling-errors)
- [Using a Different Language for the API Handler](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#using-a-different-language-for-the-api-handler)

I believe these will fulfill your needs. Lmk if not 🙂

If you have any questions or need further assistance, feel free to reach out. I'm happy to help! Thanks!

**Comment by wuhanjun** [comment]
So efficient, thank you very much. I'll give it a try.

**Comment by wuhanjun** [comment]
Speaking of which, would it be better to open up a request API? It will return a promise. If someone else wants to customize the processing of request parameters, or handle the results of responses, etc., you will need to add other methods or properties. Haha, I want to hear your opinion.

**Comment by arshad-yaseen** [comment]
I gotcha! Stay tuned for it.

**Comment by yield-ray** [comment]
Adding an option to customize the `fetch` function might be an alternative way.
(This would also let us know if it's making a network request.)

**Comment by arshad-yaseen** [comment]
Yeah, I was thinking about a `requestHandler` option that receives the params include body processed by MonacoPilot and performs any custom logic you want. However, it must return the completion text that can be inserted in the editor, so you can customize the fetch request however you'd like.

For example:

```javascript
registerCompletion(monaco, editor, {
  endpoint: 'https://api.example.com/complete',
  requestHandler: async (requestParams) => {
    // Add custom headers
    requestParams.headers['Authorization'] = 'Bearer my-token';
    
    // Modify the body
    requestParams.body.customField = 'customValue';
    
    try {
      // Perform the fetch with async/await
      const response = await fetch(requestParams.endpoint, {
        method: 'POST',
        headers: requestParams.headers,
        body: JSON.stringify(requestParams.body),
      });
      
      const data = await response.json();
      
      // Custom processing
      if (data.error) {
        // Handle error
        console.error('Custom Error Handling:', data.error);
        return null;
      }
      
      // Return the completion text
      return data.completion;
    } catch (error) {
      console.error('Fetch error:', error);
      return null;
    }
  }
});

What do you think? Is this what you wanted, @yield-ray @wuhanjun?

**Comment by arshad-yaseen** [comment]
Update `monacopilot` to `v0.11.2` 🎉. Here's the [Custom Request Handler](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#custom-request-handler). Let me know what you think, and feel free to provide any feedback or ask any questions. I'm here to help!

**Comment by arshad-yaseen** [comment]
@wuhanjun
