### ISSUE TITLE
how disable cache?

### ISSUE THREAD

**Issue by yanxiyue** [arshad-yaseen/monacopilot#56]
How can I disable the default enabled cache feature?

**Comment by arshad-yaseen** [comment]
There is no way to do it yet @yanxiyue. But count on it, Adding it very soon!

**Comment by arshad-yaseen** [comment]
Update `monacopilot` to v0.12.2 🎉 and refer to the [Caching Completions](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#caching-completions) documentation.
