### ISSUE TITLE
Code completion returns the same response on the same line when the content of the line is changed

### ISSUE THREAD

**Issue by Thimows** [arshad-yaseen/monacopilot#57]
First of all, this repo is amazing. Thanks for the great work!

- `monacopilot` version: 0.11.8
- `monaco-editor` version: 0.52.0

**What you did:**
I added content to the editor for the "onDemand" autocomplete feature, but when I change the content on the same line the same autocomplete is returned. This also seems to be happing when the trigger is not "onDemand" but one of the other options.

**What happened:**

https://github.com/user-attachments/assets/3da2c685-54fc-4b99-8f62-482e1648c580

Maybe this is a caching issue? Would be great if we could turn that off or if the feature recognizes that the content changes. If you need more information let me know!

**Comment by arshad-yaseen** [comment]
@Thimows Yeah, noted. Pushing the fix very soon! Count on it.

**Comment by Thimows** [comment]
Thank you @arshad-yaseen!

**Comment by arshad-yaseen** [comment]
This issue has been resolved in [v0.12.3](https://github.com/arshad-yaseen/monacopilot/releases/tag/v0.12.3). Please update to monacopilot `v0.12.3` at your earliest convenience. Appreciate your patience and support.

**Comment by arshad-yaseen** [comment]
If you need to disable the caching behavior for completions, please refer to the following: [Caching Completions](https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#caching-completions).
