### ISSUE TITLE
Autocompletion not being triggered on some cases

### ISSUE THREAD

**Issue by perfectbase** [arshad-yaseen/monacopilot#92]
First, Thank you for the initiative of building this package! I learned a lot from it and I couldn't find other similar open-source solutions out there.

### Issue

I noticed 2 problems with completions not triggering:
1. The completion does not trigger before the 3rd character.
2. The completion does not trigger after some other completion was accepted in the same line until you type 10 characters.

Demo:

https://github.com/user-attachments/assets/a4578b52-802a-4b11-a9f3-3a0f8f23bd95

I noticed that this is different from what I'm used to with GitHub copilot and I couldn't find a way to configure it.

Below is the experience with GitHub Copilot:

https://github.com/user-attachments/assets/c443cd5e-3847-4e74-aeff-2f0f6b2f0eea

### Possible solution

I was able to find the places where this is being set:
https://github.com/arshad-yaseen/monacopilot/blob/v0.15.14/src/utils/context-parser.ts#L21-L23
https://github.com/arshad-yaseen/monacopilot/blob/v0.15.14/src/classes/completion-cache.ts#L11

I think it would be great to be able to configure these values. Also, if there is a specific reason for this to be set this way, I would love to know it.

I would love to contribute, but I'm not sure I'll be able to find time for it.

### Versions

- `monacopilot` version: `0.15.14`
- `monaco-editor` version: `0.52.2`
- `@monaco-editor/react`: `4.6.0`
- `node` version: `22.12.0`

**Comment by arshad-yaseen** [comment]
@perfectbase Sure, I understood! Will take a look and fix it 🙌

**Comment by arshad-yaseen** [comment]
Hey @perfectbase, Fixed it in [v0.16.0](https://github.com/arshad-yaseen/monacopilot/releases/tag/v0.16.0) 🚀 Please update Monacopilot to this version.

**Comment by perfectbase** [comment]
@arshad-yaseen Thank you for the fast fix!! Just tried it! Closing the issue.
